name: "Staging"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  deploy-staging:
    name: "Staging Deploy"
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: ${{ github.repository }}
    environment: 
      name: staging
      url: https://did-registrar-staging.cheqd.net/api-docs

    steps:
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: did-registrar-staging

      - name: Load Docker image
        run: docker image load --input did-registrar-staging.tar

      - name: Push image to GitHub Container Registry
        run: docker image push --all-tags ghcr.io/${{ env.IMAGE_NAME }}

      - name: Push images to DOCR
        run: docker image push --all-tags registry.digitalocean.com/${{ env.IMAGE_NAME }}
